#!/bin/sh

if [ ! -d "$HOME/.dotfiles" ]; then
    echo "Installing dotfiles..."
    echo ""

    git clone https://github.com/luonet/dotfiles.git "$HOME/.dotfiles"
    cd "$HOME/.dotfiles"
    if [ "$1" ]; then
      rake install_$1
    else
      rake
    fi

    echo "Done."
else
    echo "$HOME/.dotfiles already exist."
fi
