#!/bin/sh

if [ ! -d "$HOME/.dotfiles" ]; then
    echo "===================================================================="
    echo "Welcome to luonet's vim and other dotfiles installation."
    echo "===================================================================="
    echo ""

    git clone https://github.com/luonet/dotfiles.git "$HOME/.dotfiles"
    cd "$HOME/.dotfiles"
    if [ "$1" ]; then
      rake install_$1
    else
      rake
    fi

    echo "===================================================================="
    echo "Done."
    echo "===================================================================="
else
    echo "$HOME/.dotfiles already exist."
fi
